---
title: "Untitled"
author: ""
output:
  tufte::tufte_html: default
---
tufte::tufte_html

```{r, include=FALSE}
library(mosaic)
library(pander)
library(readr)
library(tidyverse)
library(knitr)
library(ggplot2)
library(viridis)
library(ggeasy)
```


```{r, error=FALSE, include=FALSE}
my_data2 <- read_csv('C:/Users/jscot/Documents/Econometrics_R/hprice2.csv')

my_data <- select(my_data2, c(median_price, crime_per_capita, rooms, distance, log_nox, nox))

lognox <- my_data$log_nox


Crime<-c(my_data2$crime_per_capita)
Price<-c(my_data2$median_price)
Rooms<-c(my_data2$rooms)
PT<-c(c(my_data2$land_tax))
#NOX<-c(my_data2$)
#Distance<-c(Homework$Distance)



log_Regression <- lm(median_price ~ rooms + crime_per_capita + log_nox, data = my_data)

Normal_Regression <- lm(median_price ~ rooms + crime_per_capita + nox, data = my_data)
```

```{r, error=FALSE}
pander(summary(log_Regression))
pander(summary(Normal_Regression))
```


```{r, error=FALSE}
wage <- read_csv('C:/Users/jscot/Documents/Econometrics_R/wage2.csv')

My_wage <- select(wage, c(wage, education, expereince))

My_wage1 =  lm(wage ~ education + expereince +education*expereince, data = My_wage)
pander(summary(My_wage1))
```

