---
title: "Data Orgainizing"
author: "Mikey Tolman"
date: "6/11/2020"
output: tufte::tufte_html
---

The Following data is all of the oil that the US imports. 

```{r Set up, message=FALSE, warning=FALSE}

library(tidyverse)
library(readxl)
library(pander)
library(ggplot2)
library(car)
library(pastecs)
library(knitr)

oil <- read_excel("~/Intro Econometrics/Data Orgainizing/PET_MOVE.xlsx")

attach(oil)

head(oil)

names(oil)
```


```{r Involved countries, message=FALSE, warning=FALSE}

saudi_arabia = Saudi_to_US
united_arab = Arab_to_US

mod1 <- lm(`Total Imports` ~ OPEC_to_US + `NON-OPEC_to_US` + saudi_arabia + Russia_to_US + Canada_to_US)

summary(mod1)

plot(`NON-OPEC_to_US` ~ Date, data = oil,
     xlab = "Year", ylab = "Barrels of oil",
     main = "Non-opec countries \n exporting to USA")

plot(OPEC_to_US ~ Date, data = oil,
     xlab = "Year", ylab = "Barrels of oil",
     main = "OPEC countries \n exporting to USA")

```

```{r ranges,message=FALSE, warning=FALSE}
options(scipen = 999)
options(digits = 2)

kable(stat.desc(`Total Imports`))

kable(stat.desc(OPEC_to_US))

kable(stat.desc(`NON-OPEC_to_US`))

kable(stat.desc(saudi_arabia))

kable(stat.desc(Russia_to_US))

kable(stat.desc(Canada_to_US))


```

Africa oil

```{r africa, warning=FALSE, message=FALSE}

africaoil <- read_excel("~/Intro Econometrics/Data Orgainizing/AfricaOil.xlsx")

attach(africaoil)

names(africaoil)

head(africaoil)
```



```{r more africa, warning=FALSE, message=FALSE}


plot(Combined_Countries ~ Date, data = africaoil,
     xlab = "Year", ylab = "Barrels of oil",
     main = "African countries \n exporting oil to USA")


```

```{r data, warning=FALSE, message=FALSE}

kable(stat.desc(Combined_Countries))

```

